### ISSUE TITLE
Polylogarithm

### ISSUE THREAD

**Issue by MartinMikkelsen** [MartinMikkelsen/FewSpecialFunctions.jl#6]
Implement the polylogarithm (maybe just the dilogarithm at first). Perhaps using the following integral representation
```math
\text{Li}_s(z)= \frac{z}{\Gamma(s)} \int_0^1 \frac{|\log(y)^{s-1}|}{1-yz} \, \text{d}y
```
Consider branch at $z=1$.

[Numerical implementation](https://arxiv.org/abs/math/0702243)
[Polylogarithm](https://dlmf.nist.gov/25.12)

**Comment by longemen3000** [comment]
for polylogarithms, there is https://github.com/Expander/PolyLog.jl

**Comment by MartinMikkelsen** [comment]
Ahh thanks @longemen3000, didn't know about that one
